// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=runner_mock.go -package=git
//

// Package git is a generated GoMock package.
package git

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// GetBranchRemote mocks base method.
func (m *MockRunner) GetBranchRemote(branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchRemote", branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranchRemote indicates an expected call of GetBranchRemote.
func (mr *MockRunnerMockRecorder) GetBranchRemote(branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchRemote", reflect.TypeOf((*MockRunner)(nil).GetBranchRemote), branch)
}

// GetCurrentBranch mocks base method.
func (m *MockRunner) GetCurrentBranch() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBranch")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBranch indicates an expected call of GetCurrentBranch.
func (mr *MockRunnerMockRecorder) GetCurrentBranch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBranch", reflect.TypeOf((*MockRunner)(nil).GetCurrentBranch))
}

// GetModifiedFiles mocks base method.
func (m *MockRunner) GetModifiedFiles() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModifiedFiles")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModifiedFiles indicates an expected call of GetModifiedFiles.
func (mr *MockRunnerMockRecorder) GetModifiedFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModifiedFiles", reflect.TypeOf((*MockRunner)(nil).GetModifiedFiles))
}

// GetRemoteURL mocks base method.
func (m *MockRunner) GetRemoteURL(remote string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteURL", remote)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteURL indicates an expected call of GetRemoteURL.
func (mr *MockRunnerMockRecorder) GetRemoteURL(remote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteURL", reflect.TypeOf((*MockRunner)(nil).GetRemoteURL), remote)
}

// GetRemotes mocks base method.
func (m *MockRunner) GetRemotes() (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemotes")
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemotes indicates an expected call of GetRemotes.
func (mr *MockRunnerMockRecorder) GetRemotes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemotes", reflect.TypeOf((*MockRunner)(nil).GetRemotes))
}

// GetRepoRoot mocks base method.
func (m *MockRunner) GetRepoRoot() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoRoot")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoRoot indicates an expected call of GetRepoRoot.
func (mr *MockRunnerMockRecorder) GetRepoRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoRoot", reflect.TypeOf((*MockRunner)(nil).GetRepoRoot))
}

// GetStagedFiles mocks base method.
func (m *MockRunner) GetStagedFiles() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStagedFiles")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStagedFiles indicates an expected call of GetStagedFiles.
func (mr *MockRunnerMockRecorder) GetStagedFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStagedFiles", reflect.TypeOf((*MockRunner)(nil).GetStagedFiles))
}

// GetUntrackedFiles mocks base method.
func (m *MockRunner) GetUntrackedFiles() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUntrackedFiles")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUntrackedFiles indicates an expected call of GetUntrackedFiles.
func (mr *MockRunnerMockRecorder) GetUntrackedFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUntrackedFiles", reflect.TypeOf((*MockRunner)(nil).GetUntrackedFiles))
}

// IsInRepo mocks base method.
func (m *MockRunner) IsInRepo() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInRepo")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInRepo indicates an expected call of IsInRepo.
func (mr *MockRunnerMockRecorder) IsInRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInRepo", reflect.TypeOf((*MockRunner)(nil).IsInRepo))
}
