// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InfoRequest is an empty request for plugin metadata.
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// InfoResponse contains plugin metadata.
type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique plugin identifier.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin version (semver recommended).
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// description is a human-readable description of what the plugin does.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// author is the plugin author or organization.
	Author string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	// url is a link to the plugin's homepage or documentation.
	Url           string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *InfoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ValidateRequest contains the context passed to plugin validators.
type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type is the hook event type ("PreToolUse", "PostToolUse", "Notification").
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// tool_name is the tool being invoked ("Bash", "Write", "Edit", etc.).
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// command is the shell command (for Bash tool).
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// file_path is the file path (for file operations).
	FilePath string `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// content is the file content (for Write/Edit tools).
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// old_string is the string to replace (for Edit tool).
	OldString string `protobuf:"bytes,6,opt,name=old_string,json=oldString,proto3" json:"old_string,omitempty"`
	// new_string is the replacement string (for Edit tool).
	NewString string `protobuf:"bytes,7,opt,name=new_string,json=newString,proto3" json:"new_string,omitempty"`
	// pattern is the search pattern (for Grep/Glob tools).
	Pattern string `protobuf:"bytes,8,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// config contains plugin-specific configuration from the config file.
	Config        map[string]string `protobuf:"bytes,9,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ValidateRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ValidateRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ValidateRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ValidateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ValidateRequest) GetOldString() string {
	if x != nil {
		return x.OldString
	}
	return ""
}

func (x *ValidateRequest) GetNewString() string {
	if x != nil {
		return x.NewString
	}
	return ""
}

func (x *ValidateRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ValidateRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// ValidateResponse contains the validation result returned by a plugin.
type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// passed indicates whether the validation passed.
	Passed bool `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	// should_block indicates whether this failure should block the operation.
	ShouldBlock bool `protobuf:"varint,2,opt,name=should_block,json=shouldBlock,proto3" json:"should_block,omitempty"`
	// message is a human-readable message describing the result.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// error_code is a unique identifier for this error type.
	ErrorCode string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// fix_hint provides a short suggestion for fixing the issue.
	FixHint string `protobuf:"bytes,5,opt,name=fix_hint,json=fixHint,proto3" json:"fix_hint,omitempty"`
	// doc_link is a URL to detailed documentation for this error.
	DocLink string `protobuf:"bytes,6,opt,name=doc_link,json=docLink,proto3" json:"doc_link,omitempty"`
	// details contains additional structured information about the result.
	Details       map[string]string `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ValidateResponse) GetShouldBlock() bool {
	if x != nil {
		return x.ShouldBlock
	}
	return false
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ValidateResponse) GetFixHint() string {
	if x != nil {
		return x.FixHint
	}
	return ""
}

func (x *ValidateResponse) GetDocLink() string {
	if x != nil {
		return x.DocLink
	}
	return ""
}

func (x *ValidateResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\tplugin.v1\"\r\n" +
	"\vInfoRequest\"\x88\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"\xf1\x02\n" +
	"\x0fValidateRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"old_string\x18\x06 \x01(\tR\toldString\x12\x1d\n" +
	"\n" +
	"new_string\x18\a \x01(\tR\tnewString\x12\x18\n" +
	"\apattern\x18\b \x01(\tR\apattern\x12>\n" +
	"\x06config\x18\t \x03(\v2&.plugin.v1.ValidateRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x02\n" +
	"\x10ValidateResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12!\n" +
	"\fshould_block\x18\x02 \x01(\bR\vshouldBlock\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x19\n" +
	"\bfix_hint\x18\x05 \x01(\tR\afixHint\x12\x19\n" +
	"\bdoc_link\x18\x06 \x01(\tR\adocLink\x12B\n" +
	"\adetails\x18\a \x03(\v2(.plugin.v1.ValidateResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8f\x01\n" +
	"\x0fValidatorPlugin\x127\n" +
	"\x04Info\x12\x16.plugin.v1.InfoRequest\x1a\x17.plugin.v1.InfoResponse\x12C\n" +
	"\bValidate\x12\x1a.plugin.v1.ValidateRequest\x1a\x1b.plugin.v1.ValidateResponseB\x96\x01\n" +
	"\rcom.plugin.v1B\vPluginProtoP\x01Z3github.com/smykla-labs/klaudiush/plugin/v1;pluginv1\xa2\x02\x03PXX\xaa\x02\tPlugin.V1\xca\x02\tPlugin\\V1\xe2\x02\x15Plugin\\V1\\GPBMetadata\xea\x02\n" +
	"Plugin::V1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(*InfoRequest)(nil),      // 0: plugin.v1.InfoRequest
	(*InfoResponse)(nil),     // 1: plugin.v1.InfoResponse
	(*ValidateRequest)(nil),  // 2: plugin.v1.ValidateRequest
	(*ValidateResponse)(nil), // 3: plugin.v1.ValidateResponse
	nil,                      // 4: plugin.v1.ValidateRequest.ConfigEntry
	nil,                      // 5: plugin.v1.ValidateResponse.DetailsEntry
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	4, // 0: plugin.v1.ValidateRequest.config:type_name -> plugin.v1.ValidateRequest.ConfigEntry
	5, // 1: plugin.v1.ValidateResponse.details:type_name -> plugin.v1.ValidateResponse.DetailsEntry
	0, // 2: plugin.v1.ValidatorPlugin.Info:input_type -> plugin.v1.InfoRequest
	2, // 3: plugin.v1.ValidatorPlugin.Validate:input_type -> plugin.v1.ValidateRequest
	1, // 4: plugin.v1.ValidatorPlugin.Info:output_type -> plugin.v1.InfoResponse
	3, // 5: plugin.v1.ValidatorPlugin.Validate:output_type -> plugin.v1.ValidateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
