// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidatorPlugin_Info_FullMethodName     = "/plugin.v1.ValidatorPlugin/Info"
	ValidatorPlugin_Validate_FullMethodName = "/plugin.v1.ValidatorPlugin/Validate"
)

// ValidatorPluginClient is the client API for ValidatorPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ValidatorPlugin defines the gRPC service for external validator plugins.
type ValidatorPluginClient interface {
	// Info returns metadata about the plugin.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// Validate performs validation and returns a result.
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type validatorPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatorPluginClient(cc grpc.ClientConnInterface) ValidatorPluginClient {
	return &validatorPluginClient{cc}
}

func (c *validatorPluginClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, ValidatorPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorPluginClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, ValidatorPlugin_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorPluginServer is the server API for ValidatorPlugin service.
// All implementations must embed UnimplementedValidatorPluginServer
// for forward compatibility.
//
// ValidatorPlugin defines the gRPC service for external validator plugins.
type ValidatorPluginServer interface {
	// Info returns metadata about the plugin.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// Validate performs validation and returns a result.
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedValidatorPluginServer()
}

// UnimplementedValidatorPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidatorPluginServer struct{}

func (UnimplementedValidatorPluginServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedValidatorPluginServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedValidatorPluginServer) mustEmbedUnimplementedValidatorPluginServer() {}
func (UnimplementedValidatorPluginServer) testEmbeddedByValue()                         {}

// UnsafeValidatorPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidatorPluginServer will
// result in compilation errors.
type UnsafeValidatorPluginServer interface {
	mustEmbedUnimplementedValidatorPluginServer()
}

func RegisterValidatorPluginServer(s grpc.ServiceRegistrar, srv ValidatorPluginServer) {
	// If the following call pancis, it indicates UnimplementedValidatorPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidatorPlugin_ServiceDesc, srv)
}

func _ValidatorPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidatorPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorPluginServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidatorPlugin_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorPluginServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidatorPlugin_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorPluginServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidatorPlugin_ServiceDesc is the grpc.ServiceDesc for ValidatorPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidatorPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.ValidatorPlugin",
	HandlerType: (*ValidatorPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _ValidatorPlugin_Info_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _ValidatorPlugin_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/plugin.proto",
}
