// Code generated by MockGen. DO NOT EDIT.
// Source: rules_check.go
//
// Generated by this command:
//
//	mockgen -source=rules_check.go -destination=rules_check_mock.go -package=ruleschecker
//

// Package ruleschecker is a generated GoMock package.
package ruleschecker

import (
	reflect "reflect"

	config "github.com/smykla-labs/klaudiush/pkg/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigLoader is a mock of ConfigLoader interface.
type MockConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *MockConfigLoaderMockRecorder
	isgomock struct{}
}

// MockConfigLoaderMockRecorder is the mock recorder for MockConfigLoader.
type MockConfigLoaderMockRecorder struct {
	mock *MockConfigLoader
}

// NewMockConfigLoader creates a new mock instance.
func NewMockConfigLoader(ctrl *gomock.Controller) *MockConfigLoader {
	mock := &MockConfigLoader{ctrl: ctrl}
	mock.recorder = &MockConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigLoader) EXPECT() *MockConfigLoaderMockRecorder {
	return m.recorder
}

// HasProjectConfig mocks base method.
func (m *MockConfigLoader) HasProjectConfig() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProjectConfig")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProjectConfig indicates an expected call of HasProjectConfig.
func (mr *MockConfigLoaderMockRecorder) HasProjectConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProjectConfig", reflect.TypeOf((*MockConfigLoader)(nil).HasProjectConfig))
}

// Load mocks base method.
func (m *MockConfigLoader) Load(flags map[string]any) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", flags)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigLoaderMockRecorder) Load(flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigLoader)(nil).Load), flags)
}

// LoadWithoutValidation mocks base method.
func (m *MockConfigLoader) LoadWithoutValidation(flags map[string]any) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadWithoutValidation", flags)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadWithoutValidation indicates an expected call of LoadWithoutValidation.
func (mr *MockConfigLoaderMockRecorder) LoadWithoutValidation(flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadWithoutValidation", reflect.TypeOf((*MockConfigLoader)(nil).LoadWithoutValidation), flags)
}
