# GoReleaser configuration for klaudiush
# See https://goreleaser.com for documentation
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: klaudiush

before:
  hooks:
    - go mod tidy

builds:
  - id: klaudiush
    main: ./cmd/klaudiush
    binary: klaudiush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: checksums.txt
  algorithm: sha256

# GPG signing for checksums and archives
signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - '${signature}'
      - --detach-sign
      - '${artifact}'

# Software Bill of Materials (SBOM)
sboms:
  - artifacts: archive
    documents:
      - '${artifact}.sbom.json'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  use: github
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: ^.*feat(\([^)]*\))?:.*$
      order: 0
    - title: Bug Fixes
      regexp: ^.*fix(\([^)]*\))?:.*$
      order: 1
    - title: Documentation
      regexp: ^.*docs(\([^)]*\))?:.*$
      order: 2
    - title: CI/CD
      regexp: ^.*ci(\([^)]*\))?:.*$
      order: 3
    - title: Tests
      regexp: ^.*test(\([^)]*\))?:.*$
      order: 4
    - title: Refactoring
      regexp: ^.*refactor(\([^)]*\))?:.*$
      order: 5
    - title: Chores
      regexp: ^.*chore(\([^)]*\))?:.*$
      order: 6
    - title: Other
      order: 999
  filters:
    exclude:
      - '^Merge pull request'
      - '^Merge branch'

release:
  github:
    owner: smykla-skalski
    name: klaudiush
  prerelease: auto
  draft: false
  name_template: 'v{{ .Version }}'
  header: |
    ## klaudiush v{{ .Version }}

    Claude Code hooks validator for enforcing git workflow standards and commit message conventions.
  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install smykla-skalski/tap/klaudiush
    ```

    ### Install script
    ```bash
    curl -sSfL https://klaudiu.sh/install.sh | sh
    ```

    ### Nix
    Available via nixpkgs or flake (`github:smykla-skalski/klaudiush?dir=nix`)

    ## Verification

    ### Checksums
    SHA256 checksums are available in `checksums.txt`:
    ```bash
    sha256sum -c checksums.txt 2>&1 | grep OK
    ```

    ### GPG Signatures
    All checksums are signed with GPG:
    ```bash
    # Import public key (first time)
    gpg --keyserver keys.openpgp.org --recv-keys C1F468CD7B3DB219CFFEC99821DC3AC33C4EF676

    # Verify signature
    gpg --verify checksums.txt.sig checksums.txt
    ```

    ### SLSA Provenance
    ```bash
    gh attestation verify klaudiush_{{ .Version }}_linux_amd64.tar.gz --owner smykla-skalski
    ```

    ---
    **Full Changelog**: https://github.com/smykla-skalski/klaudiush/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - repository:
      owner: smykla-skalski
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    commit_msg_template: "chore(formula): update klaudiush to {{ .Tag }}"
    homepage: https://github.com/smykla-skalski/klaudiush
    description: "Validation dispatcher for Claude Code hooks"
    license: MIT

    install: |
      bin.install "klaudiush"
      generate_completions_from_executable(bin/"klaudiush", "completion")

    test: |
      system "#{bin}/klaudiush", "--version"
      system "#{bin}/klaudiush", "doctor", "--help"

    caveats: |
      To enable klaudiush as a Claude Code hook dispatcher:

        klaudiush init --global

      Documentation: https://github.com/smykla-skalski/klaudiush
