# Semantic Release configuration
# See https://semantic-release.gitbook.io for documentation

branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  # Analyze commits to determine version bump
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
      # noinspection YAMLIncompatibleTypes
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: docs
          release: false
        - type: style
          release: false
        - type: chore
          release: false
        - type: test
          release: false
        - type: ci
          release: false
        - type: build
          release: false
        # Breaking changes always trigger major release
        - breaking: true
          release: major

  # Generate release notes
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: perf
            section: Performance Improvements
          - type: refactor
            section: Code Refactoring
          - type: docs
            section: Documentation
            hidden: true
          - type: style
            section: Styles
            hidden: true
          - type: chore
            section: Maintenance
            hidden: true
          - type: test
            section: Tests
            hidden: true
          - type: ci
            section: CI/CD
            hidden: true
          - type: build
            section: Build System
            hidden: true

  # Update CHANGELOG.md
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: |-
        # Changelog

        All notable changes to klaudiush will be documented in this file.

        The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
        and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

  # Note: nix/package.nix (version and hashes) is updated automatically by the
  # update-nix-hashes job in .github/workflows/release.yml after GoReleaser uploads artifacts

  # Create git tag and GitHub release (GoReleaser handles the actual release)
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      message: 'chore(release): ${nextRelease.version} [skip ci]'
