coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*_test.go"
  - "**/*_mock.go"
  - "**/testdata/**"
  - "tmp/**"
  - "cmd/**"
  - "internal/doctor/fixers/**"
