version: '3'

# Task runner configuration for klaudiush
# Uses mise for tool version management
# Run 'mise install' before running tasks

vars:
  BINARY_NAME: klaudiush
  INSTALL_DIR:
    sh: |
      if [ -d "$HOME/.local/bin" ]; then
        echo "$HOME/.local/bin"
      elif [ -d "$HOME/bin" ]; then
        echo "$HOME/bin"
      elif [ -d "$HOME/.bin" ]; then
        echo "$HOME/.bin"
      else
        echo "$HOME/.local/bin"
      fi
  INSTALL_PATH: '{{.INSTALL_DIR}}/klaudiush'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  generate:
    desc: Run go generate for enumer code generation
    cmds:
      - mise exec -- go generate ./...
    sources:
      - pkg/hook/context.go
      - pkg/config/types.go
      - pkg/logger/level.go
    generates:
      - pkg/hook/eventtype_enumer.go
      - pkg/hook/tooltype_enumer.go
      - pkg/config/severity_enumer.go
      - pkg/logger/level_enumer.go

  build:
    desc: Build the binary (without signoff validation)
    deps:
      - generate
    cmds:
      - mise exec -- go build -o bin/{{.BINARY_NAME}} ./cmd/klaudiush
    sources:
      - '**/*.go'
    generates:
      - bin/{{.BINARY_NAME}}

  build:prod:
    desc: Build production binary (same as build, signoff now configured via config file)
    cmds:
      - task: build

  test:
    desc: Run all tests
    cmds:
      - mise exec -- go test -v -race -cover ./...

  test:unit:
    desc: Run unit tests only
    cmds:
      - mise exec -- go test -v -race -cover -short ./...

  test:integration:
    desc: Run integration tests only
    cmds:
      - mise exec -- go test -v -race -cover -run Integration ./...

  test:staged:
    desc: Run tests for packages with staged files
    vars:
      STAGED_FILES:
        sh: git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true
      MODIFIED_FILES:
        sh: git diff --name-only --diff-filter=ACM | grep '\.go$' || true
      ALL_CHANGED_FILES:
        sh: |
          (git diff --cached --name-only --diff-filter=ACM; git diff --name-only --diff-filter=ACM) | \
          grep '\.go$' | sort -u || true
      CHANGED_PACKAGES:
        sh: |
          files=$( (git diff --cached --name-only --diff-filter=ACM; git diff --name-only --diff-filter=ACM) | \
                  grep '\.go$' | sort -u || true )
          if [ -z "$files" ]; then
            echo ""
          else
            echo "$files" | xargs -n1 dirname | sort -u | sed 's|^|./|' | sed 's|$|/...|' | tr '\n' ' '
          fi
    cmds:
      - |
        if [ -n "{{.CHANGED_PACKAGES}}" ]; then
          echo "Running tests for changed packages..."
          mise exec -- go test -v -race -cover -short {{.CHANGED_PACKAGES}}
        else
          echo "No Go files changed, skipping tests"
        fi

  lint:
    desc: Run linters on all files
    cmds:
      - mise exec -- golangci-lint run

  lint:fix:
    desc: Run linters with auto-fix on all files
    cmds:
      - mise exec -- golangci-lint run --fix

  lint:staged:
    desc: Run linters on modified and staged files only
    vars:
      CHANGED_PACKAGES:
        sh: |
          files=$( (git diff --cached --name-only --diff-filter=ACM; git diff --name-only --diff-filter=ACM) | \
                  grep '\.go$' | sort -u || true )
          if [ -z "$files" ]; then
            echo ""
          else
            echo "$files" | xargs -n1 dirname | sort -u | sed 's|^|./|' | sed 's|$|/...|' | tr '\n' ' '
          fi
    cmds:
      - |
        if [ -n "{{.CHANGED_PACKAGES}}" ]; then
          echo "Linting changed files..."
          mise exec -- golangci-lint run {{.CHANGED_PACKAGES}}
        else
          echo "No Go files to lint"
        fi

  check:
    desc: Alias for lint:fix
    cmds:
      - task: lint:fix

  fmt:
    desc: Format code
    cmds:
      - mise exec -- golangci-lint run --fix

  install:
    desc: Install klaudiush binary to user PATH (~/.local/bin or ~/bin)
    deps:
      - build
    cmds:
      - mkdir -p {{.INSTALL_DIR}}
      - cp bin/{{.BINARY_NAME}} {{.INSTALL_PATH}}
      - chmod +x {{.INSTALL_PATH}}
      - echo "✓ Installed {{.BINARY_NAME}} to {{.INSTALL_PATH}}"
      - cmd: |
          if ! echo "$PATH" | grep -q "{{.INSTALL_DIR}}"; then
            echo ""
            echo "⚠️  Warning: {{.INSTALL_DIR}} is not in your PATH"
            echo "Add this to your shell profile (~/.bashrc, ~/.zshrc, etc.):"
            echo "  export PATH=\"{{.INSTALL_DIR}}:\$PATH\""
          fi
        silent: true

  install:hooks:
    desc: Install git pre-commit and pre-push hooks
    cmds:
      - |
        if [ ! -d ".git" ]; then
          echo "Error: Not a git repository"
          exit 1
        fi
      - mkdir -p .git/hooks
      - cp .githooks/pre-commit .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      - echo "✓ Pre-commit hook installed to .git/hooks/pre-commit"
      - cp .githooks/pre-push .git/hooks/pre-push
      - chmod +x .git/hooks/pre-push
      - echo "✓ Pre-push hook installed to .git/hooks/pre-push"

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf dist/
      - rm -rf build/

  deps:
    desc: Download dependencies
    cmds:
      - mise exec -- go mod download
      - mise exec -- go mod tidy

  verify:
    desc: Run all verification tasks
    cmds:
      - task: fmt
      - task: lint
      - task: test
