// Code generated by MockGen. DO NOT EDIT.
// Source: backup_checker.go
//
// Generated by this command:
//
//	mockgen -source=backup_checker.go -destination=backup_checker_mock.go -package=backupchecker
//

// Package backupchecker is a generated GoMock package.
package backupchecker

import (
	reflect "reflect"

	backup "github.com/smykla-labs/klaudiush/internal/backup"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageProvider is a mock of StorageProvider interface.
type MockStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStorageProviderMockRecorder
	isgomock struct{}
}

// MockStorageProviderMockRecorder is the mock recorder for MockStorageProvider.
type MockStorageProviderMockRecorder struct {
	mock *MockStorageProvider
}

// NewMockStorageProvider creates a new mock instance.
func NewMockStorageProvider(ctrl *gomock.Controller) *MockStorageProvider {
	mock := &MockStorageProvider{ctrl: ctrl}
	mock.recorder = &MockStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageProvider) EXPECT() *MockStorageProviderMockRecorder {
	return m.recorder
}

// GetBaseDir mocks base method.
func (m *MockStorageProvider) GetBaseDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseDir indicates an expected call of GetBaseDir.
func (mr *MockStorageProviderMockRecorder) GetBaseDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseDir", reflect.TypeOf((*MockStorageProvider)(nil).GetBaseDir))
}

// GetGlobalStorage mocks base method.
func (m *MockStorageProvider) GetGlobalStorage() (backup.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalStorage")
	ret0, _ := ret[0].(backup.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalStorage indicates an expected call of GetGlobalStorage.
func (mr *MockStorageProviderMockRecorder) GetGlobalStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalStorage", reflect.TypeOf((*MockStorageProvider)(nil).GetGlobalStorage))
}

// GetProjectStorage mocks base method.
func (m *MockStorageProvider) GetProjectStorage(projectPath string) (backup.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectStorage", projectPath)
	ret0, _ := ret[0].(backup.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectStorage indicates an expected call of GetProjectStorage.
func (mr *MockStorageProviderMockRecorder) GetProjectStorage(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectStorage", reflect.TypeOf((*MockStorageProvider)(nil).GetProjectStorage), projectPath)
}
