import { execFileSync } from "node:child_process"
import { isAbsolute, relative, resolve } from "node:path"

/**
 * GENERATED BY klaudiush for the opencode 2.x plugin API. Do not edit; changes
 * are overwritten. Regenerate with: klaudiush doctor --fix
 *
 * opencode 2.x loads only a default export {id, setup}. Tool execute.before
 * refuses by throwing; execute.after and session compaction add model-facing
 * text; the prompt hook and bus events are advisory and report on stderr.
 * permission.asked is forwarded as a notification only, because every tool
 * call already passes execute.before whatever the approval outcome.
 */
const BINARY = {{ .BinaryLiteral }}
const TIMEOUT_MS = {{ .TimeoutMs }}
const MAX_OUTPUT_BYTES = 8 * 1024 * 1024

/**
 * KLAUDIUSH_FAILURE_POLICY_MODE=block refuses tool calls klaudiush cannot
 * answer (binary missing, timeout, unreadable output); anything else lets them
 * through with a warning on stderr. The config file cannot decide this,
 * because reading it is klaudiush's job.
 */
const FAIL_CLOSED = (process.env.KLAUDIUSH_FAILURE_POLICY_MODE ?? "").trim().toLowerCase() === "block"

type KlaudiushResponse = {
  continue?: boolean
  decision?: string
  reason?: string
  stopReason?: string
  systemMessage?: string
  hookSpecificOutput?: {
    hookEventName?: string
    additionalContext?: string
  }
}

type Payload = Record<string, unknown>

/**
 * Runs klaudiush for one event and returns its parsed decision. Synchronous on
 * purpose: under Bun a promisified execFile can leave the hook waiting forever.
 * A non-zero exit that still printed a response is honored as written.
 */
function invoke(event: string, cwd: string, payload: Payload): KlaudiushResponse | null {
  let stdout: string

  try {
    stdout = execFileSync(BINARY, ["--provider", "opencode", "--event", event], {
      input: JSON.stringify(payload),
      encoding: "utf8",
      timeout: TIMEOUT_MS,
      stdio: ["pipe", "pipe", "pipe"],
      maxBuffer: MAX_OUTPUT_BYTES,
      ...(cwd ? { cwd } : {}),
    })
  } catch (error: any) {
    const answered = parseResponse(typeof error?.stdout === "string" ? error.stdout : "")
    if (answered) {
      return answered
    }

    console.error(`klaudiush: ${event} hook failed:`, error)

    return unavailable(event, "klaudiush did not answer: " + (error?.message ?? String(error)))
  }

  const trimmed = stdout.trim()
  if (!trimmed) {
    return null
  }

  const parsed = parseResponse(trimmed)
  if (!parsed) {
    console.error(`klaudiush: ${event} hook returned unparseable output`)

    return unavailable(event, "klaudiush returned unreadable output")
  }

  return parsed
}

function parseResponse(text: string): KlaudiushResponse | null {
  const trimmed = text.trim()
  if (!trimmed.startsWith("{")) return null

  try {
    return JSON.parse(trimmed) as KlaudiushResponse
  } catch {
    return null
  }
}

/** Answers for klaudiush when it could not answer itself. */
function unavailable(event: string, detail: string): KlaudiushResponse | null {
  if (!FAIL_CLOSED || event !== "tool.execute.before") {
    return null
  }

  const reason = `Validation unavailable: ${detail}. KLAUDIUSH_FAILURE_POLICY_MODE=block refuses tool calls klaudiush cannot check; ask the user to run 'klaudiush doctor'.`

  return { decision: "deny", reason, systemMessage: reason }
}

/** "deny" comes from pre-execution events, "block" from turn-stop events. */
function isBlocked(resp: KlaudiushResponse | null): boolean {
  if (!resp) return false

  const decision = resp.decision?.toLowerCase()

  return decision === "deny" || decision === "block" || resp.continue === false
}

function blockReason(resp: KlaudiushResponse | null): string {
  return (
    resp?.reason?.trim() ||
    resp?.stopReason?.trim() ||
    resp?.systemMessage?.trim() ||
    "klaudiush blocked this operation"
  )
}

function extraContext(resp: KlaudiushResponse | null): string {
  return resp?.hookSpecificOutput?.additionalContext?.trim() ?? ""
}

/** The 2.x plugin context has no toast, so user messages go to opencode's log. */
function notifyUser(event: string, resp: KlaudiushResponse | null) {
  const message = resp?.systemMessage?.trim()
  if (message) {
    console.error(`klaudiush: ${event}: ${message}`)
  }
}

function appendText(parts: unknown, text: string) {
  if (text && Array.isArray(parts)) {
    parts.push({ type: "text", text })
  }
}

/**
 * Refuses moving the session out of the directory this plugin instance
 * validates. After a move opencode starts a new instance bound to the target,
 * so klaudiush would resolve project config and protection from there and stop
 * guarding this project's files.
 */
function sessionMoveEscape(tool: unknown, input: any, cwd: string): string {
  if (typeof tool !== "string" || !tool.endsWith("session_move") || !cwd) {
    return ""
  }

  const target = typeof input?.directory === "string" ? input.directory : ""
  if (!target) {
    return ""
  }

  const inside = relative(cwd, resolve(cwd, target))
  if (inside === "" || (!inside.startsWith("..") && !isAbsolute(inside))) {
    return ""
  }

  return `klaudiush: moving the session to ${target} leaves ${cwd}, where klaudiush enforces this project's policy. Start a new opencode session in that directory instead.`
}

type Registration = { dispose: () => unknown }

/**
 * Registers a hook that cannot refuse anything. A failure is logged instead of
 * thrown: a rejected setup makes opencode drop the whole plugin, and with it
 * the execute.before gate that is already registered.
 */
async function registerAdvisory(
  registrations: Registration[],
  event: string,
  register: () => Promise<Registration>,
) {
  try {
    registrations.push(await register())
  } catch (error) {
    console.error(`klaudiush: could not register ${event}:`, error)
  }
}

/**
 * Each plugin instance is bound to one location, the directory the session
 * runs in, which is where the validators resolve project config and git state.
 */
async function setup(ctx: any) {
  const cwd: string = ctx?.location?.directory ?? ""

  const base = (event: string, sessionID?: string): Payload => ({
    hook_event_name: event,
    session_id: sessionID ?? "",
    cwd,
  })

  const report = (event: string, payload: Payload) => {
    const resp = invoke(event, cwd, payload)
    notifyUser(event, resp)

    return resp
  }

  const registrations: Registration[] = []

  registrations.push(
    await ctx.tool.hook("execute.before", (event: any) => {
      const escape = sessionMoveEscape(event.tool, event.input, cwd)
      if (escape) {
        throw new Error(escape)
      }

      const resp = invoke("tool.execute.before", cwd, {
        ...base("tool.execute.before", event.sessionID),
        tool_name: event.tool,
        tool_input: event.input,
        tool_use_id: event.id,
      })

      notifyUser("tool.execute.before", resp)

      if (isBlocked(resp)) {
        throw new Error(blockReason(resp))
      }
    }),
  )

  await registerAdvisory(registrations, "tool.execute.after", () =>
    ctx.tool.hook("execute.after", (event: any) => {
      const resp = report("tool.execute.after", {
        ...base("tool.execute.after", event.sessionID),
        tool_name: event.tool,
        tool_input: event.input,
        tool_use_id: event.id,
      })

      const context = extraContext(resp)

      if (event.status === "completed") {
        appendText(event.result?.content, context)
      } else if (context && typeof event.error?.message === "string") {
        event.error.message = event.error.message + "\n\n" + context
      }
    }),
  )

  await registerAdvisory(registrations, "chat.message", () =>
    ctx.session.hook("prompt", (event: any) => {
      report("chat.message", {
        ...base("chat.message", event.sessionID),
        tool_input: { content: event.prompt?.text ?? "" },
      })
    }),
  )

  await registerAdvisory(registrations, "session.compacting", () =>
    ctx.session.hook("compaction", (event: any) => {
      const resp = report("session.compacting", base("session.compacting", event.sessionID))

      appendText(event.system, extraContext(resp))
    }),
  )

  const forward = (event: any) => {
    const data = event?.data ?? {}

    switch (event?.type) {
      case "session.created":
        report("session.created", {
          ...base("session.created", data.sessionID),
          source: data.parentID ? "subagent" : "startup",
        })

        return

      case "session.execution.succeeded":
      case "session.execution.interrupted":
        report("session.idle", base("session.idle", data.sessionID))

        return

      case "session.execution.failed":
        report("session.idle", {
          ...base("session.idle", data.sessionID),
          message: data.error?.message ?? data.error?.type ?? "session error",
        })

        return

      case "session.compaction.ended":
        report("session.compacted", base("session.compacted", data.sessionID))

        return

      case "permission.asked":
        report("permission.asked", {
          ...base("permission.asked", data.sessionID),
          notification_type: data.action ?? "",
          message: data.message ?? "",
        })

        return

      default:
        return
    }
  }

  const controller = new AbortController()

  void (async () => {
    try {
      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
        forward(event)
      }
    } catch (error) {
      if (!controller.signal.aborted) {
        console.error("klaudiush: event stream failed:", error)
      }
    }
  })()

  return async () => {
    controller.abort()

    for (const registration of registrations) {
      try {
        await registration.dispose()
      } catch (error) {
        console.error("klaudiush: hook cleanup failed:", error)
      }
    }
  }
}

export default { id: "klaudiush", setup }
