// GENERATED BY klaudiush. Do not edit; changes are overwritten.
// Regenerate with: klaudiush doctor --fix
//
// Bridges opencode's plugin hooks onto the klaudiush validator. opencode has no
// declarative hook config, so the integration ships as this plugin instead of a
// JSON settings block like Claude, Codex, and Gemini use.
//
// What each hook can do about a finding is fixed by opencode's hook signatures:
//
//   tool.execute.before   can refuse, by throwing
//   tool.execute.after    can add model-facing text, by appending to the result
//   session.compacting    can add model-facing text, by pushing onto the prompt
//   chat.message, event   neither; findings reach the user as a toast only
//
// permission.ask is intentionally not registered. Every tool call already
// passes through tool.execute.before whatever the approval outcome, so
// forwarding the approval prompt too would validate one call twice and
// double-charge the exception rate limiter.
import { execFileSync } from "node:child_process"

const BINARY = {{ .BinaryLiteral }}
const TIMEOUT_MS = {{ .TimeoutMs }}
const MAX_OUTPUT_BYTES = 8 * 1024 * 1024

// klaudiush answers every failure it can catch itself. When it cannot answer
// at all (binary missing, killed at the timeout, unreadable output) this
// plugin decides: KLAUDIUSH_FAILURE_POLICY_MODE=block refuses the tool call,
// anything else lets it through with a warning on stderr. The config file
// cannot decide this, because reading it is klaudiush's job.
const FAIL_CLOSED = (process.env.KLAUDIUSH_FAILURE_POLICY_MODE ?? "").trim().toLowerCase() === "block"

// opencode walks every export of a plugin file and calls each one *as a plugin*:
// a non-function export throws, and an exported helper runs with the plugin
// input. Everything below therefore stays module-local except the single plugin
// export at the bottom.

type KlaudiushResponse = {
  continue?: boolean
  decision?: string
  reason?: string
  stopReason?: string
  systemMessage?: string
  hookSpecificOutput?: {
    hookEventName?: string
    additionalContext?: string
  }
}

type Payload = Record<string, unknown>

// invoke runs klaudiush for one event and returns its parsed decision.
//
// **Synchronous on purpose.** Under the Bun runtime opencode embeds, a
// promisified execFile never settles: the hook awaits forever, the request never
// completes, and the session hangs with no error. execFileSync is what the other
// klaudiush-adjacent plugins on this machine use for the same reason.
//
// Every failure path fails *open* unless FAIL_CLOSED is set, and then only
// for tool.execute.before, the one hook that can refuse anything. A missing
// binary, a timeout, a crash, or unparseable output resolve to "no opinion".
// klaudiush itself exits 0 with a response for the failures it catches, so a
// non-zero exit that still printed a response is honored as written.
function invoke(event: string, cwd: string, payload: Payload): KlaudiushResponse | null {
  let stdout: string

  try {
    stdout = execFileSync(BINARY, ["--provider", "opencode", "--event", event], {
      input: JSON.stringify(payload),
      encoding: "utf8",
      timeout: TIMEOUT_MS,
      stdio: ["pipe", "pipe", "pipe"],
      maxBuffer: MAX_OUTPUT_BYTES,
      // The validators resolve project config and git state from the process
      // directory, and only trust a provider-reported directory for the
      // providers that cannot run a shell. Without this the dispatcher would
      // inspect whichever directory opencode was launched from, which is the
      // wrong repository whenever the session runs in another worktree.
      ...(cwd ? { cwd } : {}),
    })
  } catch (error: any) {
    const answered = parseResponse(typeof error?.stdout === "string" ? error.stdout : "")
    if (answered) {
      return answered
    }

    // Loud on stderr, which opencode captures, because a silent fail-open is
    // indistinguishable from "everything passed": a moved or deleted binary
    // would otherwise disable validation for the whole session with no signal.
    console.error(`klaudiush: ${event} hook failed:`, error)

    return unavailable(event, "klaudiush did not answer: " + (error?.message ?? String(error)))
  }

  const trimmed = stdout.trim()
  if (!trimmed) {
    // A clean pass writes nothing at all.
    return null
  }

  const parsed = parseResponse(trimmed)
  if (!parsed) {
    console.error(`klaudiush: ${event} hook returned unparseable output`)

    return unavailable(event, "klaudiush returned unreadable output")
  }

  return parsed
}

function parseResponse(text: string): KlaudiushResponse | null {
  const trimmed = text.trim()
  if (!trimmed.startsWith("{")) return null

  try {
    return JSON.parse(trimmed) as KlaudiushResponse
  } catch {
    return null
  }
}

// unavailable answers for klaudiush when it could not answer itself.
function unavailable(event: string, detail: string): KlaudiushResponse | null {
  if (!FAIL_CLOSED || event !== "tool.execute.before") {
    return null
  }

  const reason = `Validation unavailable: ${detail}. KLAUDIUSH_FAILURE_POLICY_MODE=block refuses tool calls klaudiush cannot check; ask the user to run 'klaudiush doctor'.`

  return { decision: "deny", reason, systemMessage: reason }
}

// isBlocked reports whether klaudiush refused the operation. "deny" comes from
// pre-execution events, "block" from turn-stop events.
function isBlocked(resp: KlaudiushResponse | null): boolean {
  if (!resp) return false

  const decision = resp.decision?.toLowerCase()

  return decision === "deny" || decision === "block" || resp.continue === false
}

function blockReason(resp: KlaudiushResponse | null): string {
  return (
    resp?.reason?.trim() ||
    resp?.stopReason?.trim() ||
    resp?.systemMessage?.trim() ||
    "klaudiush blocked this operation"
  )
}

function extraContext(resp: KlaudiushResponse | null): string {
  return resp?.hookSpecificOutput?.additionalContext?.trim() ?? ""
}

export const Klaudiush = async ({ client, directory, worktree }: any) => {
  // Validators resolve project config and git state from this path, so prefer
  // the worktree root over whatever subdirectory the session started in.
  const cwd = worktree || directory

  const toast = async (resp: KlaudiushResponse | null, variant: string) => {
    const message = resp?.systemMessage?.trim()
    if (!message) return

    try {
      await client.tui.showToast({
        body: { title: "klaudiush", message, variant },
      })
    } catch {
      // A session must not fail because a toast could not be drawn.
    }
  }

  const base = (event: string, sessionID?: string): Payload => ({
    hook_event_name: event,
    session_id: sessionID ?? "",
    cwd,
  })

  // report forwards an advisory (non-decisive) event and surfaces any message.
  const report = async (event: string, payload: Payload) => {
    const resp = invoke(event, cwd, payload)
    await toast(resp, isBlocked(resp) ? "warning" : "info")

    return resp
  }

  return {
    // Decisive pre-execution gate. Throwing aborts the tool call and hands the
    // reason to the model, which is opencode's only way to refuse a tool.
    "tool.execute.before": async (input: any, output: any) => {
      const resp = invoke("tool.execute.before", cwd, {
        ...base("tool.execute.before", input.sessionID),
        tool_name: input.tool,
        tool_input: output.args,
        tool_use_id: input.callID,
      })

      if (isBlocked(resp)) {
        await toast(resp, "error")

        throw new Error(blockReason(resp))
      }

      await toast(resp, "warning")
    },

    // Advisory: the tool already ran. Findings are appended to the tool output
    // so the model reads them as part of the result.
    "tool.execute.after": async (input: any, output: any) => {
      const resp = invoke("tool.execute.after", cwd, {
        ...base("tool.execute.after", input.sessionID),
        tool_name: input.tool,
        tool_input: input.args,
        tool_use_id: input.callID,
      })

      const context = extraContext(resp)
      if (context) {
        output.output = output.output ? output.output + "\n\n" + context : context
      }

      await toast(resp, isBlocked(resp) ? "warning" : "info")
    },

    // Advisory only: this hook returns void, so a prompt cannot be refused.
    // The prompt text lives in the sibling parts array, not on the message,
    // which carries only ids and metadata.
    "chat.message": async (input: any, output: any) => {
      const promptText = (output.parts ?? [])
        .filter((part: any) => part?.type === "text" && typeof part.text === "string")
        .map((part: any) => part.text)
        .join("\n")

      await report("chat.message", {
        ...base("chat.message", input.sessionID),
        model: input.model ? input.model.providerID + "/" + input.model.modelID : "",
        tool_input: { content: promptText },
      })
    },

    // Pre-compaction: klaudiush findings are injected into the compaction
    // prompt so they survive into the summarized context.
    "experimental.session.compacting": async (input: any, output: any) => {
      const resp = invoke(
        "session.compacting",
        cwd,
        base("session.compacting", input.sessionID),
      )

      const context = extraContext(resp)
      if (context) {
        output.context.push(context)
      }
    },

    event: async ({ event }: any) => {
      switch (event.type) {
        case "session.created": {
          const info = event.properties?.info ?? {}
          await report("session.created", {
            ...base("session.created", info.id),
            // A child session is a subagent run; Claude splits these into
            // SessionStart and SubagentStart.
            source: info.parentID ? "subagent" : "startup",
          })

          return
        }

        case "session.idle": {
          await report("session.idle", base("session.idle", event.properties?.sessionID))

          return
        }

        case "session.error": {
          const resp = invoke("session.idle", cwd, {
            ...base("session.idle", event.properties?.sessionID),
            message: event.properties?.error?.name ?? "session error",
          })

          await toast(resp, "error")

          return
        }

        case "session.compacted": {
          await report(
            "session.compacted",
            base("session.compacted", event.properties?.sessionID),
          )

          return
        }

        // A pending approval is opencode's closest analogue to a Claude
        // Notification: the session is waiting on the user. The event has been
        // renamed across opencode versions, so both spellings are handled.
        case "permission.asked":
        case "permission.updated": {
          await report("permission.asked", {
            ...base("permission.asked", event.properties?.sessionID),
            notification_type: event.properties?.type ?? "",
            message: event.properties?.title ?? "",
          })

          return
        }

        default:
          return
      }
    },
  }
}
