// Code generated by "enumer -type=Level -trimprefix=Level -transform=upper -json -text -yaml -sql"; DO NOT EDIT.

package logger

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
	"github.com/cockroachdb/errors"
)

const _LevelName = "DEBUGINFOERROR"

var _LevelIndex = [...]uint8{0, 5, 9, 14}

const _LevelLowerName = "debuginfoerror"

func (i Level) String() string {
	if i < 0 || i >= Level(len(_LevelIndex)-1) {
		return fmt.Sprintf("Level(%d)", i)
	}
	return _LevelName[_LevelIndex[i]:_LevelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LevelNoOp() {
	var x [1]struct{}
	_ = x[LevelDebug-(0)]
	_ = x[LevelInfo-(1)]
	_ = x[LevelError-(2)]
}

var _LevelValues = []Level{LevelDebug, LevelInfo, LevelError}

var _LevelNameToValueMap = map[string]Level{
	_LevelName[0:5]:       LevelDebug,
	_LevelLowerName[0:5]:  LevelDebug,
	_LevelName[5:9]:       LevelInfo,
	_LevelLowerName[5:9]:  LevelInfo,
	_LevelName[9:14]:      LevelError,
	_LevelLowerName[9:14]: LevelError,
}

var _LevelNames = []string{
	_LevelName[0:5],
	_LevelName[5:9],
	_LevelName[9:14],
}

// LevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LevelString(s string) (Level, error) {
	if val, ok := _LevelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LevelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Newf("%s does not belong to Level values", s)
}

// LevelValues returns all values of the enum
func LevelValues() []Level {
	return _LevelValues
}

// LevelStrings returns a slice of all String values of the enum
func LevelStrings() []string {
	strs := make([]string, len(_LevelNames))
	copy(strs, _LevelNames)
	return strs
}

// IsALevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Level) IsALevel() bool {
	for _, v := range _LevelValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Level
func (i Level) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Level
func (i *Level) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return errors.Newf("Level should be a string, got %s", data)
	}

	var err error
	*i, err = LevelString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Level
func (i Level) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Level
func (i *Level) UnmarshalText(text []byte) error {
	var err error
	*i, err = LevelString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Level
func (i Level) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Level
func (i *Level) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = LevelString(s)
	return err
}

func (i Level) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Level) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return errors.Newf("invalid value of Level: %[1]T(%[1]v)", value)
	}

	val, err := LevelString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
