// Code generated by "enumer -type=AuditAction -trimprefix=AuditAction -json -text -yaml -sql -output=audit_action_enumer.go"; DO NOT EDIT.

package session

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
	"github.com/cockroachdb/errors"
)

const _AuditActionName = "PoisonUnpoison"

var _AuditActionIndex = [...]uint8{0, 6, 14}

const _AuditActionLowerName = "poisonunpoison"

func (i AuditAction) String() string {
	if i < 0 || i >= AuditAction(len(_AuditActionIndex)-1) {
		return fmt.Sprintf("AuditAction(%d)", i)
	}
	return _AuditActionName[_AuditActionIndex[i]:_AuditActionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AuditActionNoOp() {
	var x [1]struct{}
	_ = x[AuditActionPoison-(0)]
	_ = x[AuditActionUnpoison-(1)]
}

var _AuditActionValues = []AuditAction{AuditActionPoison, AuditActionUnpoison}

var _AuditActionNameToValueMap = map[string]AuditAction{
	_AuditActionName[0:6]:       AuditActionPoison,
	_AuditActionLowerName[0:6]:  AuditActionPoison,
	_AuditActionName[6:14]:      AuditActionUnpoison,
	_AuditActionLowerName[6:14]: AuditActionUnpoison,
}

var _AuditActionNames = []string{
	_AuditActionName[0:6],
	_AuditActionName[6:14],
}

// AuditActionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AuditActionString(s string) (AuditAction, error) {
	if val, ok := _AuditActionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AuditActionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Newf("%s does not belong to AuditAction values", s)
}

// AuditActionValues returns all values of the enum
func AuditActionValues() []AuditAction {
	return _AuditActionValues
}

// AuditActionStrings returns a slice of all String values of the enum
func AuditActionStrings() []string {
	strs := make([]string, len(_AuditActionNames))
	copy(strs, _AuditActionNames)
	return strs
}

// IsAAuditAction returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AuditAction) IsAAuditAction() bool {
	for _, v := range _AuditActionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AuditAction
func (i AuditAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AuditAction
func (i *AuditAction) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return errors.Newf("AuditAction should be a string, got %s", data)
	}

	var err error
	*i, err = AuditActionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AuditAction
func (i AuditAction) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AuditAction
func (i *AuditAction) UnmarshalText(text []byte) error {
	var err error
	*i, err = AuditActionString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for AuditAction
func (i AuditAction) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for AuditAction
func (i *AuditAction) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = AuditActionString(s)
	return err
}

func (i AuditAction) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *AuditAction) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return errors.Newf("invalid value of AuditAction: %[1]T(%[1]v)", value)
	}

	val, err := AuditActionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
