// Code generated by MockGen. DO NOT EDIT.
// Source: config_check.go
//
// Generated by this command:
//
//	mockgen -source=config_check.go -destination=config_loader_mock.go -package=configchecker
//

// Package configchecker is a generated GoMock package.
package configchecker

import (
	reflect "reflect"

	config "github.com/smykla-labs/klaudiush/pkg/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigLoader is a mock of ConfigLoader interface.
type MockConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *MockConfigLoaderMockRecorder
	isgomock struct{}
}

// MockConfigLoaderMockRecorder is the mock recorder for MockConfigLoader.
type MockConfigLoaderMockRecorder struct {
	mock *MockConfigLoader
}

// NewMockConfigLoader creates a new mock instance.
func NewMockConfigLoader(ctrl *gomock.Controller) *MockConfigLoader {
	mock := &MockConfigLoader{ctrl: ctrl}
	mock.recorder = &MockConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigLoader) EXPECT() *MockConfigLoaderMockRecorder {
	return m.recorder
}

// GlobalConfigPath mocks base method.
func (m *MockConfigLoader) GlobalConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GlobalConfigPath indicates an expected call of GlobalConfigPath.
func (mr *MockConfigLoaderMockRecorder) GlobalConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalConfigPath", reflect.TypeOf((*MockConfigLoader)(nil).GlobalConfigPath))
}

// HasGlobalConfig mocks base method.
func (m *MockConfigLoader) HasGlobalConfig() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasGlobalConfig")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasGlobalConfig indicates an expected call of HasGlobalConfig.
func (mr *MockConfigLoaderMockRecorder) HasGlobalConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasGlobalConfig", reflect.TypeOf((*MockConfigLoader)(nil).HasGlobalConfig))
}

// HasProjectConfig mocks base method.
func (m *MockConfigLoader) HasProjectConfig() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProjectConfig")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProjectConfig indicates an expected call of HasProjectConfig.
func (mr *MockConfigLoaderMockRecorder) HasProjectConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProjectConfig", reflect.TypeOf((*MockConfigLoader)(nil).HasProjectConfig))
}

// Load mocks base method.
func (m *MockConfigLoader) Load(flags map[string]any) (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", flags)
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigLoaderMockRecorder) Load(flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigLoader)(nil).Load), flags)
}
