// Code generated by MockGen. DO NOT EDIT.
// Source: command.go
//
// Generated by this command:
//
//	mockgen -source=command.go -destination=command_mock.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockCommandRunner) Run(ctx context.Context, name string, args ...string) CommandResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(CommandResult)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCommandRunnerMockRecorder) Run(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommandRunner)(nil).Run), varargs...)
}

// RunWithStdin mocks base method.
func (m *MockCommandRunner) RunWithStdin(ctx context.Context, stdin io.Reader, name string, args ...string) CommandResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx, stdin, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWithStdin", varargs...)
	ret0, _ := ret[0].(CommandResult)
	return ret0
}

// RunWithStdin indicates an expected call of RunWithStdin.
func (mr *MockCommandRunnerMockRecorder) RunWithStdin(ctx, stdin, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, stdin, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithStdin", reflect.TypeOf((*MockCommandRunner)(nil).RunWithStdin), varargs...)
}

// RunWithTimeout mocks base method.
func (m *MockCommandRunner) RunWithTimeout(timeout time.Duration, name string, args ...string) CommandResult {
	m.ctrl.T.Helper()
	varargs := []any{timeout, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWithTimeout", varargs...)
	ret0, _ := ret[0].(CommandResult)
	return ret0
}

// RunWithTimeout indicates an expected call of RunWithTimeout.
func (mr *MockCommandRunnerMockRecorder) RunWithTimeout(timeout, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{timeout, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithTimeout", reflect.TypeOf((*MockCommandRunner)(nil).RunWithTimeout), varargs...)
}
