// Code generated by MockGen. DO NOT EDIT.
// Source: tempfile.go
//
// Generated by this command:
//
//	mockgen -source=tempfile.go -destination=tempfile_mock.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTempFileManager is a mock of TempFileManager interface.
type MockTempFileManager struct {
	ctrl     *gomock.Controller
	recorder *MockTempFileManagerMockRecorder
	isgomock struct{}
}

// MockTempFileManagerMockRecorder is the mock recorder for MockTempFileManager.
type MockTempFileManagerMockRecorder struct {
	mock *MockTempFileManager
}

// NewMockTempFileManager creates a new mock instance.
func NewMockTempFileManager(ctrl *gomock.Controller) *MockTempFileManager {
	mock := &MockTempFileManager{ctrl: ctrl}
	mock.recorder = &MockTempFileManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTempFileManager) EXPECT() *MockTempFileManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTempFileManager) Create(pattern, content string) (string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", pattern, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockTempFileManagerMockRecorder) Create(pattern, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTempFileManager)(nil).Create), pattern, content)
}
