package suggest

import (
	"github.com/smykla-skalski/klaudiush/internal/templates"
)

//nolint:gochecknoglobals // package-level template is the intended pattern
var klaudiushMDTemplate = templates.Parse("klaudiush-md", templateText)

const templateText = `<!-- klaudiush:hash:{{.Hash}} -->
# KLAUDIUSH.md

<!-- Auto-generated by klaudiush suggest (v{{.Version}}). Do not edit. -->
{{- if .Commit}}

## Commits

` + "`git commit {{join .Commit.RequiredFlags \" \"}} -m \"type(scope): description\"`" + `
{{- if .Commit.ConventionalCommit}}

Types: {{join .Commit.ValidTypes ", "}}
{{- end}}
Title ≤{{.Commit.TitleMaxLength}} chars. Body lines ≤{{.Commit.BodyMaxLineLength}} chars.
{{- if .Commit.CheckStagingArea}}
Stage files before committing.
{{- end}}
{{- if .Commit.BlockInfraScope}}
Use ` + "`ci(...)`" + `/` + "`test(...)`" + ` not ` + "`feat(ci)`" + `/` + "`fix(test)`" + `.
{{- end}}
{{- if .Commit.BlockPRReferences}}
No PR references (#123) in commit messages.
{{- end}}
{{- if .Commit.BlockAIAttribution}}
No AI attribution in commit messages.
{{- end}}
{{- if .Commit.ForbiddenPatterns}}
Forbidden: {{join .Commit.ForbiddenPatterns ", "}}
{{- end}}
{{- end}}
{{- if .Push}}

## Push
{{- if .Push.BlockedRemotes}}

Never push to: {{join .Push.BlockedRemotes ", "}}
{{- end}}
{{- if .Push.RequireTracking}}
Always push to tracked branch.
{{- end}}
{{- end}}
{{- if .Branch}}
{{- if .Branch.RequireType}}

## Branches

Format: ` + "`type/description`" + ` — types: {{join .Branch.ValidTypes ", "}}
{{- if not .Branch.AllowUppercase}}
Lowercase only.
{{- end}}
{{- end}}
{{- end}}
{{- if .PR}}

## PRs

Title ≤{{.PR.TitleMaxLength}} chars.{{if .PR.RequireBody}} Body required.{{end}}
{{- end}}
{{- if .Linters}}

## Linters

{{- range .Linters}}
- {{.FileType}} → {{.Tool}}
{{- end}}
{{- end}}
{{- if .Secrets}}
{{- if .Secrets.BlockOnDetection}}

## Secrets

Never commit API keys, tokens, passwords, or private keys.
{{- end}}
{{- end}}
{{- if .Shell}}
{{- if .Shell.CheckAllCommands}}

## Shell

Escape backticks in all commands. Use single quotes when no variable interpolation needed.
{{- end}}
{{- end}}
{{- if .Rules}}

## Custom Rules

{{- range .Rules}}
- {{.Name}} ({{.Validator}}): {{.Action}}
{{- end}}
{{- end}}
{{- if .Cascades}}

## Cascades

{{- range .Cascades}}
- {{.SourceCode}} fix → expect {{.TargetCode}}
{{- end}}
{{- end}}
`
