// Code generated by "enumer -type=Severity -trimprefix=Severity -transform=lower -json -text -yaml -sql"; DO NOT EDIT.

package config

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
	"github.com/cockroachdb/errors"
)

const _SeverityName = "unknownerrorwarning"

var _SeverityIndex = [...]uint8{0, 7, 12, 19}

const _SeverityLowerName = "unknownerrorwarning"

func (i Severity) String() string {
	if i < 0 || i >= Severity(len(_SeverityIndex)-1) {
		return fmt.Sprintf("Severity(%d)", i)
	}
	return _SeverityName[_SeverityIndex[i]:_SeverityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SeverityNoOp() {
	var x [1]struct{}
	_ = x[SeverityUnknown-(0)]
	_ = x[SeverityError-(1)]
	_ = x[SeverityWarning-(2)]
}

var _SeverityValues = []Severity{SeverityUnknown, SeverityError, SeverityWarning}

var _SeverityNameToValueMap = map[string]Severity{
	_SeverityName[0:7]:        SeverityUnknown,
	_SeverityLowerName[0:7]:   SeverityUnknown,
	_SeverityName[7:12]:       SeverityError,
	_SeverityLowerName[7:12]:  SeverityError,
	_SeverityName[12:19]:      SeverityWarning,
	_SeverityLowerName[12:19]: SeverityWarning,
}

var _SeverityNames = []string{
	_SeverityName[0:7],
	_SeverityName[7:12],
	_SeverityName[12:19],
}

// SeverityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SeverityString(s string) (Severity, error) {
	if val, ok := _SeverityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SeverityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Newf("%s does not belong to Severity values", s)
}

// SeverityValues returns all values of the enum
func SeverityValues() []Severity {
	return _SeverityValues
}

// SeverityStrings returns a slice of all String values of the enum
func SeverityStrings() []string {
	strs := make([]string, len(_SeverityNames))
	copy(strs, _SeverityNames)
	return strs
}

// IsASeverity returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Severity) IsASeverity() bool {
	for _, v := range _SeverityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Severity
func (i Severity) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Severity
func (i *Severity) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return errors.Newf("Severity should be a string, got %s", data)
	}

	var err error
	*i, err = SeverityString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Severity
func (i Severity) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Severity
func (i *Severity) UnmarshalText(text []byte) error {
	var err error
	*i, err = SeverityString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Severity
func (i Severity) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Severity
func (i *Severity) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = SeverityString(s)
	return err
}

func (i Severity) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Severity) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return errors.Newf("invalid value of Severity: %[1]T(%[1]v)", value)
	}

	val, err := SeverityString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
