// Code generated by MockGen. DO NOT EDIT.
// Source: actionlint.go
//
// Generated by this command:
//
//	mockgen -source=actionlint.go -destination=actionlint_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActionLinter is a mock of ActionLinter interface.
type MockActionLinter struct {
	ctrl     *gomock.Controller
	recorder *MockActionLinterMockRecorder
	isgomock struct{}
}

// MockActionLinterMockRecorder is the mock recorder for MockActionLinter.
type MockActionLinterMockRecorder struct {
	mock *MockActionLinter
}

// NewMockActionLinter creates a new mock instance.
func NewMockActionLinter(ctrl *gomock.Controller) *MockActionLinter {
	mock := &MockActionLinter{ctrl: ctrl}
	mock.recorder = &MockActionLinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionLinter) EXPECT() *MockActionLinterMockRecorder {
	return m.recorder
}

// Lint mocks base method.
func (m *MockActionLinter) Lint(ctx context.Context, content, filePath string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lint", ctx, content, filePath)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Lint indicates an expected call of Lint.
func (mr *MockActionLinterMockRecorder) Lint(ctx, content, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lint", reflect.TypeOf((*MockActionLinter)(nil).Lint), ctx, content, filePath)
}
