// Code generated by MockGen. DO NOT EDIT.
// Source: gitleaks.go
//
// Generated by this command:
//
//	mockgen -source=gitleaks.go -destination=gitleaks_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitleaksChecker is a mock of GitleaksChecker interface.
type MockGitleaksChecker struct {
	ctrl     *gomock.Controller
	recorder *MockGitleaksCheckerMockRecorder
	isgomock struct{}
}

// MockGitleaksCheckerMockRecorder is the mock recorder for MockGitleaksChecker.
type MockGitleaksCheckerMockRecorder struct {
	mock *MockGitleaksChecker
}

// NewMockGitleaksChecker creates a new mock instance.
func NewMockGitleaksChecker(ctrl *gomock.Controller) *MockGitleaksChecker {
	mock := &MockGitleaksChecker{ctrl: ctrl}
	mock.recorder = &MockGitleaksCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitleaksChecker) EXPECT() *MockGitleaksCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockGitleaksChecker) Check(ctx context.Context, content string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, content)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockGitleaksCheckerMockRecorder) Check(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockGitleaksChecker)(nil).Check), ctx, content)
}

// IsAvailable mocks base method.
func (m *MockGitleaksChecker) IsAvailable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockGitleaksCheckerMockRecorder) IsAvailable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockGitleaksChecker)(nil).IsAvailable))
}
