// Code generated by MockGen. DO NOT EDIT.
// Source: gofumpt.go
//
// Generated by this command:
//
//	mockgen -source=gofumpt.go -destination=gofumpt_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGofumptChecker is a mock of GofumptChecker interface.
type MockGofumptChecker struct {
	ctrl     *gomock.Controller
	recorder *MockGofumptCheckerMockRecorder
	isgomock struct{}
}

// MockGofumptCheckerMockRecorder is the mock recorder for MockGofumptChecker.
type MockGofumptCheckerMockRecorder struct {
	mock *MockGofumptChecker
}

// NewMockGofumptChecker creates a new mock instance.
func NewMockGofumptChecker(ctrl *gomock.Controller) *MockGofumptChecker {
	mock := &MockGofumptChecker{ctrl: ctrl}
	mock.recorder = &MockGofumptCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGofumptChecker) EXPECT() *MockGofumptCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockGofumptChecker) Check(ctx context.Context, content string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, content)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockGofumptCheckerMockRecorder) Check(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockGofumptChecker)(nil).Check), ctx, content)
}

// CheckWithOptions mocks base method.
func (m *MockGofumptChecker) CheckWithOptions(ctx context.Context, content string, opts *GofumptOptions) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWithOptions", ctx, content, opts)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// CheckWithOptions indicates an expected call of CheckWithOptions.
func (mr *MockGofumptCheckerMockRecorder) CheckWithOptions(ctx, content, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWithOptions", reflect.TypeOf((*MockGofumptChecker)(nil).CheckWithOptions), ctx, content, opts)
}
