// Code generated by MockGen. DO NOT EDIT.
// Source: markdownlint.go
//
// Generated by this command:
//
//	mockgen -source=markdownlint.go -destination=markdownlint_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	validators "github.com/smykla-labs/klaudiush/internal/validators"
	gomock "go.uber.org/mock/gomock"
)

// MockMarkdownLinter is a mock of MarkdownLinter interface.
type MockMarkdownLinter struct {
	ctrl     *gomock.Controller
	recorder *MockMarkdownLinterMockRecorder
	isgomock struct{}
}

// MockMarkdownLinterMockRecorder is the mock recorder for MockMarkdownLinter.
type MockMarkdownLinterMockRecorder struct {
	mock *MockMarkdownLinter
}

// NewMockMarkdownLinter creates a new mock instance.
func NewMockMarkdownLinter(ctrl *gomock.Controller) *MockMarkdownLinter {
	mock := &MockMarkdownLinter{ctrl: ctrl}
	mock.recorder = &MockMarkdownLinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarkdownLinter) EXPECT() *MockMarkdownLinterMockRecorder {
	return m.recorder
}

// Lint mocks base method.
func (m *MockMarkdownLinter) Lint(ctx context.Context, content string, initialState *validators.MarkdownState) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lint", ctx, content, initialState)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Lint indicates an expected call of Lint.
func (mr *MockMarkdownLinterMockRecorder) Lint(ctx, content, initialState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lint", reflect.TypeOf((*MockMarkdownLinter)(nil).Lint), ctx, content, initialState)
}

// LintWithPath mocks base method.
func (m *MockMarkdownLinter) LintWithPath(ctx context.Context, content string, initialState *validators.MarkdownState, originalPath string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LintWithPath", ctx, content, initialState, originalPath)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// LintWithPath indicates an expected call of LintWithPath.
func (mr *MockMarkdownLinterMockRecorder) LintWithPath(ctx, content, initialState, originalPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LintWithPath", reflect.TypeOf((*MockMarkdownLinter)(nil).LintWithPath), ctx, content, initialState, originalPath)
}
