// Code generated by MockGen. DO NOT EDIT.
// Source: oxlint.go
//
// Generated by this command:
//
//	mockgen -source=oxlint.go -destination=oxlint_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOxlintChecker is a mock of OxlintChecker interface.
type MockOxlintChecker struct {
	ctrl     *gomock.Controller
	recorder *MockOxlintCheckerMockRecorder
	isgomock struct{}
}

// MockOxlintCheckerMockRecorder is the mock recorder for MockOxlintChecker.
type MockOxlintCheckerMockRecorder struct {
	mock *MockOxlintChecker
}

// NewMockOxlintChecker creates a new mock instance.
func NewMockOxlintChecker(ctrl *gomock.Controller) *MockOxlintChecker {
	mock := &MockOxlintChecker{ctrl: ctrl}
	mock.recorder = &MockOxlintCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOxlintChecker) EXPECT() *MockOxlintCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockOxlintChecker) Check(ctx context.Context, content string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, content)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockOxlintCheckerMockRecorder) Check(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockOxlintChecker)(nil).Check), ctx, content)
}

// CheckWithOptions mocks base method.
func (m *MockOxlintChecker) CheckWithOptions(ctx context.Context, content string, opts *OxlintCheckOptions) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWithOptions", ctx, content, opts)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// CheckWithOptions indicates an expected call of CheckWithOptions.
func (mr *MockOxlintCheckerMockRecorder) CheckWithOptions(ctx, content, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWithOptions", reflect.TypeOf((*MockOxlintChecker)(nil).CheckWithOptions), ctx, content, opts)
}
