// Code generated by MockGen. DO NOT EDIT.
// Source: ruff.go
//
// Generated by this command:
//
//	mockgen -source=ruff.go -destination=ruff_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRuffChecker is a mock of RuffChecker interface.
type MockRuffChecker struct {
	ctrl     *gomock.Controller
	recorder *MockRuffCheckerMockRecorder
	isgomock struct{}
}

// MockRuffCheckerMockRecorder is the mock recorder for MockRuffChecker.
type MockRuffCheckerMockRecorder struct {
	mock *MockRuffChecker
}

// NewMockRuffChecker creates a new mock instance.
func NewMockRuffChecker(ctrl *gomock.Controller) *MockRuffChecker {
	mock := &MockRuffChecker{ctrl: ctrl}
	mock.recorder = &MockRuffCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuffChecker) EXPECT() *MockRuffCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockRuffChecker) Check(ctx context.Context, content string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, content)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockRuffCheckerMockRecorder) Check(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockRuffChecker)(nil).Check), ctx, content)
}

// CheckWithOptions mocks base method.
func (m *MockRuffChecker) CheckWithOptions(ctx context.Context, content string, opts *RuffCheckOptions) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWithOptions", ctx, content, opts)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// CheckWithOptions indicates an expected call of CheckWithOptions.
func (mr *MockRuffCheckerMockRecorder) CheckWithOptions(ctx, content, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWithOptions", reflect.TypeOf((*MockRuffChecker)(nil).CheckWithOptions), ctx, content, opts)
}
