// Code generated by MockGen. DO NOT EDIT.
// Source: shellcheck.go
//
// Generated by this command:
//
//	mockgen -source=shellcheck.go -destination=shellcheck_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShellChecker is a mock of ShellChecker interface.
type MockShellChecker struct {
	ctrl     *gomock.Controller
	recorder *MockShellCheckerMockRecorder
	isgomock struct{}
}

// MockShellCheckerMockRecorder is the mock recorder for MockShellChecker.
type MockShellCheckerMockRecorder struct {
	mock *MockShellChecker
}

// NewMockShellChecker creates a new mock instance.
func NewMockShellChecker(ctrl *gomock.Controller) *MockShellChecker {
	mock := &MockShellChecker{ctrl: ctrl}
	mock.recorder = &MockShellCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShellChecker) EXPECT() *MockShellCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockShellChecker) Check(ctx context.Context, content string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, content)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockShellCheckerMockRecorder) Check(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockShellChecker)(nil).Check), ctx, content)
}

// CheckWithOptions mocks base method.
func (m *MockShellChecker) CheckWithOptions(ctx context.Context, content string, opts *ShellCheckOptions) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWithOptions", ctx, content, opts)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// CheckWithOptions indicates an expected call of CheckWithOptions.
func (mr *MockShellCheckerMockRecorder) CheckWithOptions(ctx, content, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWithOptions", reflect.TypeOf((*MockShellChecker)(nil).CheckWithOptions), ctx, content, opts)
}
