// Code generated by MockGen. DO NOT EDIT.
// Source: terraform.go
//
// Generated by this command:
//
//	mockgen -source=terraform.go -destination=terraform_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTerraformFormatter is a mock of TerraformFormatter interface.
type MockTerraformFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockTerraformFormatterMockRecorder
	isgomock struct{}
}

// MockTerraformFormatterMockRecorder is the mock recorder for MockTerraformFormatter.
type MockTerraformFormatterMockRecorder struct {
	mock *MockTerraformFormatter
}

// NewMockTerraformFormatter creates a new mock instance.
func NewMockTerraformFormatter(ctrl *gomock.Controller) *MockTerraformFormatter {
	mock := &MockTerraformFormatter{ctrl: ctrl}
	mock.recorder = &MockTerraformFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerraformFormatter) EXPECT() *MockTerraformFormatterMockRecorder {
	return m.recorder
}

// CheckFormat mocks base method.
func (m *MockTerraformFormatter) CheckFormat(ctx context.Context, content string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckFormat", ctx, content)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// CheckFormat indicates an expected call of CheckFormat.
func (mr *MockTerraformFormatterMockRecorder) CheckFormat(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckFormat", reflect.TypeOf((*MockTerraformFormatter)(nil).CheckFormat), ctx, content)
}

// DetectTool mocks base method.
func (m *MockTerraformFormatter) DetectTool() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectTool")
	ret0, _ := ret[0].(string)
	return ret0
}

// DetectTool indicates an expected call of DetectTool.
func (mr *MockTerraformFormatterMockRecorder) DetectTool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectTool", reflect.TypeOf((*MockTerraformFormatter)(nil).DetectTool))
}
