// Code generated by MockGen. DO NOT EDIT.
// Source: tflint.go
//
// Generated by this command:
//
//	mockgen -source=tflint.go -destination=tflint_mock.go -package=linters
//

// Package linters is a generated GoMock package.
package linters

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTfLinter is a mock of TfLinter interface.
type MockTfLinter struct {
	ctrl     *gomock.Controller
	recorder *MockTfLinterMockRecorder
	isgomock struct{}
}

// MockTfLinterMockRecorder is the mock recorder for MockTfLinter.
type MockTfLinterMockRecorder struct {
	mock *MockTfLinter
}

// NewMockTfLinter creates a new mock instance.
func NewMockTfLinter(ctrl *gomock.Controller) *MockTfLinter {
	mock := &MockTfLinter{ctrl: ctrl}
	mock.recorder = &MockTfLinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTfLinter) EXPECT() *MockTfLinterMockRecorder {
	return m.recorder
}

// Lint mocks base method.
func (m *MockTfLinter) Lint(ctx context.Context, filePath string) *LintResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lint", ctx, filePath)
	ret0, _ := ret[0].(*LintResult)
	return ret0
}

// Lint indicates an expected call of Lint.
func (mr *MockTfLinterMockRecorder) Lint(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lint", reflect.TypeOf((*MockTfLinter)(nil).Lint), ctx, filePath)
}
