// Code generated by "enumer -type=EventType -trimprefix=EventType -json -text -yaml -sql"; DO NOT EDIT.

package hook

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
	"github.com/cockroachdb/errors"
)

const _EventTypeName = "UnknownPreToolUsePostToolUseNotification"

var _EventTypeIndex = [...]uint8{0, 7, 17, 28, 40}

const _EventTypeLowerName = "unknownpretooluseposttoolusenotification"

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventTypeIndex)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventTypeName[_EventTypeIndex[i]:_EventTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EventTypeNoOp() {
	var x [1]struct{}
	_ = x[EventTypeUnknown-(0)]
	_ = x[EventTypePreToolUse-(1)]
	_ = x[EventTypePostToolUse-(2)]
	_ = x[EventTypeNotification-(3)]
}

var _EventTypeValues = []EventType{EventTypeUnknown, EventTypePreToolUse, EventTypePostToolUse, EventTypeNotification}

var _EventTypeNameToValueMap = map[string]EventType{
	_EventTypeName[0:7]:        EventTypeUnknown,
	_EventTypeLowerName[0:7]:   EventTypeUnknown,
	_EventTypeName[7:17]:       EventTypePreToolUse,
	_EventTypeLowerName[7:17]:  EventTypePreToolUse,
	_EventTypeName[17:28]:      EventTypePostToolUse,
	_EventTypeLowerName[17:28]: EventTypePostToolUse,
	_EventTypeName[28:40]:      EventTypeNotification,
	_EventTypeLowerName[28:40]: EventTypeNotification,
}

var _EventTypeNames = []string{
	_EventTypeName[0:7],
	_EventTypeName[7:17],
	_EventTypeName[17:28],
	_EventTypeName[28:40],
}

// EventTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EventTypeString(s string) (EventType, error) {
	if val, ok := _EventTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EventTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Newf("%s does not belong to EventType values", s)
}

// EventTypeValues returns all values of the enum
func EventTypeValues() []EventType {
	return _EventTypeValues
}

// EventTypeStrings returns a slice of all String values of the enum
func EventTypeStrings() []string {
	strs := make([]string, len(_EventTypeNames))
	copy(strs, _EventTypeNames)
	return strs
}

// IsAEventType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EventType) IsAEventType() bool {
	for _, v := range _EventTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EventType
func (i EventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EventType
func (i *EventType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return errors.Newf("EventType should be a string, got %s", data)
	}

	var err error
	*i, err = EventTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EventType
func (i EventType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EventType
func (i *EventType) UnmarshalText(text []byte) error {
	var err error
	*i, err = EventTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for EventType
func (i EventType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for EventType
func (i *EventType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = EventTypeString(s)
	return err
}

func (i EventType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *EventType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return errors.Newf("invalid value of EventType: %[1]T(%[1]v)", value)
	}

	val, err := EventTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
