// Code generated by "enumer -type=ToolType -trimprefix=ToolType -json -text -yaml -sql"; DO NOT EDIT.

package hook

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
	"github.com/cockroachdb/errors"
)

const _ToolTypeName = "UnknownBashWriteEditMultiEditGrepReadGlob"

var _ToolTypeIndex = [...]uint8{0, 7, 11, 16, 20, 29, 33, 37, 41}

const _ToolTypeLowerName = "unknownbashwriteeditmultieditgrepreadglob"

func (i ToolType) String() string {
	if i < 0 || i >= ToolType(len(_ToolTypeIndex)-1) {
		return fmt.Sprintf("ToolType(%d)", i)
	}
	return _ToolTypeName[_ToolTypeIndex[i]:_ToolTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ToolTypeNoOp() {
	var x [1]struct{}
	_ = x[ToolTypeUnknown-(0)]
	_ = x[ToolTypeBash-(1)]
	_ = x[ToolTypeWrite-(2)]
	_ = x[ToolTypeEdit-(3)]
	_ = x[ToolTypeMultiEdit-(4)]
	_ = x[ToolTypeGrep-(5)]
	_ = x[ToolTypeRead-(6)]
	_ = x[ToolTypeGlob-(7)]
}

var _ToolTypeValues = []ToolType{ToolTypeUnknown, ToolTypeBash, ToolTypeWrite, ToolTypeEdit, ToolTypeMultiEdit, ToolTypeGrep, ToolTypeRead, ToolTypeGlob}

var _ToolTypeNameToValueMap = map[string]ToolType{
	_ToolTypeName[0:7]:        ToolTypeUnknown,
	_ToolTypeLowerName[0:7]:   ToolTypeUnknown,
	_ToolTypeName[7:11]:       ToolTypeBash,
	_ToolTypeLowerName[7:11]:  ToolTypeBash,
	_ToolTypeName[11:16]:      ToolTypeWrite,
	_ToolTypeLowerName[11:16]: ToolTypeWrite,
	_ToolTypeName[16:20]:      ToolTypeEdit,
	_ToolTypeLowerName[16:20]: ToolTypeEdit,
	_ToolTypeName[20:29]:      ToolTypeMultiEdit,
	_ToolTypeLowerName[20:29]: ToolTypeMultiEdit,
	_ToolTypeName[29:33]:      ToolTypeGrep,
	_ToolTypeLowerName[29:33]: ToolTypeGrep,
	_ToolTypeName[33:37]:      ToolTypeRead,
	_ToolTypeLowerName[33:37]: ToolTypeRead,
	_ToolTypeName[37:41]:      ToolTypeGlob,
	_ToolTypeLowerName[37:41]: ToolTypeGlob,
}

var _ToolTypeNames = []string{
	_ToolTypeName[0:7],
	_ToolTypeName[7:11],
	_ToolTypeName[11:16],
	_ToolTypeName[16:20],
	_ToolTypeName[20:29],
	_ToolTypeName[29:33],
	_ToolTypeName[33:37],
	_ToolTypeName[37:41],
}

// ToolTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ToolTypeString(s string) (ToolType, error) {
	if val, ok := _ToolTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ToolTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, errors.Newf("%s does not belong to ToolType values", s)
}

// ToolTypeValues returns all values of the enum
func ToolTypeValues() []ToolType {
	return _ToolTypeValues
}

// ToolTypeStrings returns a slice of all String values of the enum
func ToolTypeStrings() []string {
	strs := make([]string, len(_ToolTypeNames))
	copy(strs, _ToolTypeNames)
	return strs
}

// IsAToolType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ToolType) IsAToolType() bool {
	for _, v := range _ToolTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ToolType
func (i ToolType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ToolType
func (i *ToolType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return errors.Newf("ToolType should be a string, got %s", data)
	}

	var err error
	*i, err = ToolTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ToolType
func (i ToolType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ToolType
func (i *ToolType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ToolTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for ToolType
func (i ToolType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for ToolType
func (i *ToolType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ToolTypeString(s)
	return err
}

func (i ToolType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ToolType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return errors.Newf("invalid value of ToolType: %[1]T(%[1]v)", value)
	}

	val, err := ToolTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
