// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=types_mock.go -package=doctor
//

// Package doctor is a generated GoMock package.
package doctor

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHealthChecker is a mock of HealthChecker interface.
type MockHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckerMockRecorder
	isgomock struct{}
}

// MockHealthCheckerMockRecorder is the mock recorder for MockHealthChecker.
type MockHealthCheckerMockRecorder struct {
	mock *MockHealthChecker
}

// NewMockHealthChecker creates a new mock instance.
func NewMockHealthChecker(ctrl *gomock.Controller) *MockHealthChecker {
	mock := &MockHealthChecker{ctrl: ctrl}
	mock.recorder = &MockHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthChecker) EXPECT() *MockHealthCheckerMockRecorder {
	return m.recorder
}

// Category mocks base method.
func (m *MockHealthChecker) Category() Category {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Category")
	ret0, _ := ret[0].(Category)
	return ret0
}

// Category indicates an expected call of Category.
func (mr *MockHealthCheckerMockRecorder) Category() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Category", reflect.TypeOf((*MockHealthChecker)(nil).Category))
}

// Check mocks base method.
func (m *MockHealthChecker) Check(ctx context.Context) CheckResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(CheckResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockHealthCheckerMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthChecker)(nil).Check), ctx)
}

// Name mocks base method.
func (m *MockHealthChecker) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockHealthCheckerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockHealthChecker)(nil).Name))
}

// MockFixer is a mock of Fixer interface.
type MockFixer struct {
	ctrl     *gomock.Controller
	recorder *MockFixerMockRecorder
	isgomock struct{}
}

// MockFixerMockRecorder is the mock recorder for MockFixer.
type MockFixerMockRecorder struct {
	mock *MockFixer
}

// NewMockFixer creates a new mock instance.
func NewMockFixer(ctrl *gomock.Controller) *MockFixer {
	mock := &MockFixer{ctrl: ctrl}
	mock.recorder = &MockFixerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixer) EXPECT() *MockFixerMockRecorder {
	return m.recorder
}

// CanFix mocks base method.
func (m *MockFixer) CanFix(result CheckResult) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanFix", result)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanFix indicates an expected call of CanFix.
func (mr *MockFixerMockRecorder) CanFix(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanFix", reflect.TypeOf((*MockFixer)(nil).CanFix), result)
}

// Description mocks base method.
func (m *MockFixer) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockFixerMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockFixer)(nil).Description))
}

// Fix mocks base method.
func (m *MockFixer) Fix(ctx context.Context, interactive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fix", ctx, interactive)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fix indicates an expected call of Fix.
func (mr *MockFixerMockRecorder) Fix(ctx, interactive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fix", reflect.TypeOf((*MockFixer)(nil).Fix), ctx, interactive)
}

// ID mocks base method.
func (m *MockFixer) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockFixerMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockFixer)(nil).ID))
}

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockReporter) Report(results []CheckResult, verbose bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Report", results, verbose)
}

// Report indicates an expected call of Report.
func (mr *MockReporterMockRecorder) Report(results, verbose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockReporter)(nil).Report), results, verbose)
}

// MockStreamingReporter is a mock of StreamingReporter interface.
type MockStreamingReporter struct {
	ctrl     *gomock.Controller
	recorder *MockStreamingReporterMockRecorder
	isgomock struct{}
}

// MockStreamingReporterMockRecorder is the mock recorder for MockStreamingReporter.
type MockStreamingReporterMockRecorder struct {
	mock *MockStreamingReporter
}

// NewMockStreamingReporter creates a new mock instance.
func NewMockStreamingReporter(ctrl *gomock.Controller) *MockStreamingReporter {
	mock := &MockStreamingReporter{ctrl: ctrl}
	mock.recorder = &MockStreamingReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamingReporter) EXPECT() *MockStreamingReporterMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockStreamingReporter) Report(results []CheckResult, verbose bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Report", results, verbose)
}

// Report indicates an expected call of Report.
func (mr *MockStreamingReporterMockRecorder) Report(results, verbose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockStreamingReporter)(nil).Report), results, verbose)
}

// RunAndReport mocks base method.
func (m *MockStreamingReporter) RunAndReport(ctx context.Context, registry *Registry, verbose bool, categories []Category) []CheckResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAndReport", ctx, registry, verbose, categories)
	ret0, _ := ret[0].([]CheckResult)
	return ret0
}

// RunAndReport indicates an expected call of RunAndReport.
func (mr *MockStreamingReporterMockRecorder) RunAndReport(ctx, registry, verbose, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAndReport", reflect.TypeOf((*MockStreamingReporter)(nil).RunAndReport), ctx, registry, verbose, categories)
}
