// Code generated by MockGen. DO NOT EDIT.
// Source: detector.go
//
// Generated by this command:
//
//	mockgen -source=detector.go -destination=detector_mock.go -package=secrets
//

// Package secrets is a generated GoMock package.
package secrets

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDetector is a mock of Detector interface.
type MockDetector struct {
	ctrl     *gomock.Controller
	recorder *MockDetectorMockRecorder
	isgomock struct{}
}

// MockDetectorMockRecorder is the mock recorder for MockDetector.
type MockDetectorMockRecorder struct {
	mock *MockDetector
}

// NewMockDetector creates a new mock instance.
func NewMockDetector(ctrl *gomock.Controller) *MockDetector {
	mock := &MockDetector{ctrl: ctrl}
	mock.recorder = &MockDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetector) EXPECT() *MockDetectorMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockDetector) Detect(content string) []Finding {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", content)
	ret0, _ := ret[0].([]Finding)
	return ret0
}

// Detect indicates an expected call of Detect.
func (mr *MockDetectorMockRecorder) Detect(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockDetector)(nil).Detect), content)
}
